import {Navigate,useNavigate} from 'react-router-dom'
import {useMemo,useState} from 'react'
import Header from '../components/Header'
import Button from '../components/Button'
import RoleCard from '../components/RoleCard'
import {UseLocalGame} from '../store/localGame'
import {Words} from '../data/words'
type Stage='REVEAL'|'TURNS'|'DISCUSSION'|'CHOOSE'|'RESULT'
export default function LocalGame(){const NavigateTo=useNavigate();const{Players,Round,BeginRound,Settings}=UseLocalGame();const[Stage,SetStage]=useState<Stage>('REVEAL');const[Index,SetIndex]=useState(0);const[Ready,SetReady]=useState(false);const[Selected,SetSelected]=useState<string[]>([]);if(!Round)return <Navigate to="/local" replace/>;const Word=Words.find(Entry=>Entry.Id===Round.WordId)!;const Ordered=useMemo(()=>[...Round.Assignments].sort((First,Second)=>First.TurnPosition-Second.TurnPosition),[Round]);const CurrentAssignment=Ordered[Math.min(Index,Ordered.length-1)];const CurrentPlayer=Players.find(Player=>Player.Id===CurrentAssignment?.PlayerId);const Impostors=Ordered.filter(Assignment=>Assignment.Role==='IMPOSTOR').map(Assignment=>Assignment.PlayerId);function NewRound(){BeginRound();SetStage('REVEAL');SetIndex(0);SetReady(false);SetSelected([])}
if(Stage==='REVEAL'){if(Index>=Players.length)return <main className="shell gameScreen"><Header/><section className="handoff celebrate"><div className="bigSticker">🎭</div><div className="eyebrow">ВСЕ ГОТОВЫ</div><h1>Роли розданы</h1><p>Теперь каждый даёт одну ассоциацию. Не называйте слово, не повторяйте чужие подсказки и не помогайте Импостору слишком сильно.</p><Button onClick={()=>{SetIndex(0);SetStage('TURNS')}}>Начать ходы</Button></section></main>;return <main className="shell gameScreen"><Header/>{!Ready?<section className="handoff"><div className="handoffSticker">📱</div><div className="eyebrow">ИГРОК {Index+1} ИЗ {Players.length}</div><h1>Передайте телефон</h1><div className="namePlate">{CurrentPlayer?.Name}</div><p>Убедитесь, что экран видите только вы.</p><Button onClick={()=>SetReady(true)}>Телефон у меня</Button></section>:<section className="roleStage"><RoleCard Role={CurrentAssignment.Role} Word={Word.Word} Hint={Round.Hint} Category={CurrentAssignment.Role==='PLAYER'?Round.Category:undefined}/><Button className="secondary handoffButton" onClick={()=>{SetReady(false);SetIndex(Value=>Value+1)}}>Скрыть и передать дальше</Button></section>}</main>}
if(Stage==='TURNS'){const NextPlayer=Players.find(Player=>Player.Id===Ordered[(Index+1)%Ordered.length].PlayerId);return <main className="shell gameScreen"><Header/><section className="handoff turnCard"><div className="handoffSticker">💬</div><div className="eyebrow">ХОД {Index+1} ИЗ {Players.length}</div><h1>Сейчас говорит</h1><div className="namePlate">{CurrentPlayer?.Name}</div><div className="gameFact"><span>Дальше</span><b>{NextPlayer?.Name}</b></div><p>Дайте одну ассоциацию. Лучше короткую: предмет, свойство, ситуация или действие.</p><Button onClick={()=>{if(Index+1>=Players.length){SetIndex(0);SetStage('DISCUSSION')}else SetIndex(Value=>Value+1)}}>Готово</Button></section></main>}
if(Stage==='DISCUSSION')return <main className="shell gameScreen"><Header/><section className="handoff discussionCard"><div className="handoffSticker">🗣️</div><div className="eyebrow">ОБСУЖДЕНИЕ</div><h1>Кто здесь лишний?</h1><p>Сравните ассоциации, задавайте вопросы и защищайтесь. Импостор уже мог догадаться о слове, так что не раскрывайте его в споре.</p><div className="miniRules"><span>👀 Ищите слишком общие ответы</span><span>🧩 Сверяйте ответы между собой</span><span>🤐 Не произносите секретное слово</span></div><Button onClick={()=>SetStage('CHOOSE')}>Выбрать Импостора</Button></section></main>
if(Stage==='CHOOSE'){function Toggle(PlayerId:string){SetSelected(Current=>Current.includes(PlayerId)?Current.filter(Id=>Id!==PlayerId):Current.length<Settings.ImpostorCount?[...Current,PlayerId]:Current)}return <main className="shell gameScreen"><Header/><section className="panel suspectPanel"><div className="handoffSticker">🎯</div><div className="eyebrow">ОБЩЕЕ РЕШЕНИЕ</div><h1>Кого раскрываем?</h1><p>Выберите {Settings.ImpostorCount===1?'одного игрока':`${Settings.ImpostorCount} игроков`}. В локальном режиме отдельного тайного голосования нет.</p><div className="suspectGrid">{Players.map(Player=><button key={Player.Id} className={`suspectCard ${Selected.includes(Player.Id)?'selected':''}`} onClick={()=>Toggle(Player.Id)}><span className="avatar">{Player.Name.slice(0,1).toUpperCase()}</span><b>{Player.Name}</b><span>{Selected.includes(Player.Id)?'✓':''}</span></button>)}</div><Button disabled={Selected.length!==Settings.ImpostorCount} onClick={()=>SetStage('RESULT')}>Раскрыть результат</Button></section></main>}
const Found=Selected.length===Impostors.length&&Selected.every(PlayerId=>Impostors.includes(PlayerId));return <main className="shell gameScreen"><Header/><section className={`resultHero ${Found?'successResult':'missResult'}`}><div className="resultSticker">{Found?'🎉':'😈'}</div><div className="eyebrow">РЕЗУЛЬТАТ РАУНДА</div><h1>{Found?'Импостор раскрыт!':'Импостор выжил'}</h1><p>Импостор{Impostors.length>1?'ы':''}: <b>{Players.filter(Player=>Impostors.includes(Player.Id)).map(Player=>Player.Name).join(', ')}</b></p><div className="wordReveal"><span>Загаданное слово</span><strong>{Word.Word}</strong><small>{Word.Category}</small></div></section><section className="resultActions">{Round.Number<Settings.RoundCount?<Button onClick={NewRound}>Следующий раунд · {Round.Number+1}/{Settings.RoundCount}</Button>:<Button onClick={()=>NavigateTo('/local')}>Завершить игру</Button>}<Button className="secondary" onClick={()=>NavigateTo('/local')}>В лобби</Button></section></main>}
